### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'use_memory_efficient_kernel'

### ISSUE THREAD

**Issue by brianloyal** [aqlaboratory/openfold#115]
I've been seeing an error today related to the `use_memory_efficient_kernel` argument to forward() using versions of the OpenFold code beginning with the commit on Friday, June 10 2022 ("Vastly lower peak inference memory usage"). Resetting the git version back to the last May 25, 2022 commit fixes the issue.

I'm running OpenFold via Docker on a g4dn.xlarge instance (4 vCPUs, 16 GiB Memory, 1 T4 GPU) targeting the 73-residue T1084 from CASP14 (https://predictioncenter.org/casp14/target.cgi?id=119&view=all). Same Dockerfile as in the main branch of this repo. 

Here's my command, plus the error it generates:

```
docker run \
--gpus all \
-v /home/ec2-user/data:/data \
-v /fsx/:/database/ \
-ti openfold:latest \
python3 /opt/openfold/run_pretrained_openfold.py \
/data/fasta_dir \
/database/pdb_mmcif/mmcif_files/ \
--use_precomputed_alignments /data/alignments/ \
--output_dir /data \
--model_device cuda:0 \
--jax_param_path /database/params/params_model_1.npz
```

```
Traceback (most recent call last):
  File "/opt/openfold/run_pretrained_openfold.py", line 409, in <module>
    main(args)
  File "/opt/openfold/run_pretrained_openfold.py", line 277, in main
    out = run_model(model, batch, tag, args)
  File "/opt/openfold/run_pretrained_openfold.py", line 96, in run_model
    out = model(batch)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/openfold/openfold/model/model.py", line 455, in forward
    _recycle=(num_iters > 1)
  File "/opt/openfold/openfold/model/model.py", line 293, in iteration
    no_batch_dims,
  File "/opt/openfold/openfold/model/model.py", line 171, in embed_templates
    _mask_trans=self.config._mask_trans,
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/openfold/openfold/model/template.py", line 373, in forward
    blocks_per_ckpt=self.blocks_per_ckpt if self.training else None,
  File "/opt/openfold/openfold/utils/checkpointing.py", line 77, in checkpoint_blocks
    return exec(blocks, args)
  File "/opt/openfold/openfold/utils/checkpointing.py", line 64, in exec
    a = wrap(block(*a))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/openfold/openfold/model/template.py", line 221, in forward
    use_lma=use_lma,
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'use_memory_efficient_kernel'
```

**Comment by gahdritz** [comment]
Fixed in [4bfd5bf].(https://github.com/aqlaboratory/openfold/commit/4bfd5bf0842c1da787b74dc50e7012fd3ea6066e)
