### ISSUE TITLE
ModuleNotFoundError: No module named 'attn_core_inplace_cuda'

### ISSUE THREAD

**Issue by zjyuan1208** [aqlaboratory/openfold#131]
I install the env by the script and when I run the run_pretrained_openfold.py an import error occurs.

ModuleNotFoundError: No module named 'attn_core_inplace_cuda'

**Comment by gahdritz** [comment]
Could you share the full error trace?

**Comment by adrian-jasinski** [comment]
I have similar error:

======================================================================
ERROR: tests.test_utils (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_utils
Traceback (most recent call last):
  File "/home/username/mambaforge/envs/openfold/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/username/mambaforge/envs/openfold/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/username/code/openfold/tests/test_utils.py", line 27, in <module>
    import tests.compare_utils as compare_utils
  File "/home/username/code/openfold/tests/compare_utils.py", line 12, in <module>
    from openfold.model.model import AlphaFold
  File "/home/username/code/openfold/openfold/model/model.py", line 29, in <module>
    from openfold.model.embedders import (
  File "/home/username/code/openfold/openfold/model/embedders.py", line 29, in <module>
    from openfold.model.primitives import Linear, LayerNorm
  File "/home/username/code/openfold/openfold/model/primitives.py", line 38, in <module>
    from openfold.utils.kernel.attention_core import attention_core
  File "/home/username/code/openfold/openfold/utils/kernel/attention_core.py", line 20, in <module>
    attn_core_inplace_cuda = importlib.import_module("attn_core_inplace_cuda")
  File "/home/username/mambaforge/envs/openfold/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'attn_core_inplace_cuda'
