### ISSUE TITLE
Training Runtime Error: StopIteration

### ISSUE THREAD

**Issue by Zhang690683220** [aqlaboratory/openfold#132]
Hi,

I'm using the released training data on AWS and the latest main branch to train the model.

1.  The directory structure of the released data is not recognized by the code.
2.  After re-structuring the directories and put all the .hhr and .a3m under the alignment directory, the code crashes at `File "/global/u2/b/bz186/openfold/openfold/data/data_modules.py", line 377, in reroll
    datapoint_idx = next(samples)` with default settings.

Any idea to solve this?

Thanks,

Bo

The full trace back is as below:
```
Traceback (most recent call last):
  File "train_openfold.py", line 548, in <module>
    main(args)
  File "train_openfold.py", line 341, in main
    ckpt_path=ckpt_path,
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 197, in on_run_start
    self.trainer.reset_train_val_dataloaders(self.trainer.lightning_module)
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 595, in reset_train_val_dataloaders
    self.reset_train_dataloader(model=model)
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 365, in reset_train_dataloader
    self.train_dataloader = self.request_dataloader(RunningStage.TRAINING, model=model)
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 611, in request_dataloader
    dataloader = source.dataloader()
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 300, in dataloader
    return method()
  File "/global/u2/b/bz186/openfold/openfold/data/data_modules.py", line 694, in train_dataloader
    return self._gen_dataloader("train") 
  File "/global/u2/b/bz186/openfold/openfold/data/data_modules.py", line 671, in _gen_dataloader
    dataset.reroll()
  File "/global/u2/b/bz186/openfold/openfold/data/data_modules.py", line 377, in reroll
    datapoint_idx = next(samples)
StopIteration
srun: error: nid001680: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=2466693.0
```

**Comment by Zhang690683220** [comment]
Hi,

I dug a little deeper into this bug by add the exception handling:

```
try:
     datapoint_idx = next(samples)
except StopIteration:
     print("samples.length = {}, idx = {}".format(sum(1 for _ in samples), dataset_idx))
```

but the result shows that `samples.length = 0, idx = 0`

just FYI.

Bests,

Bo

**Comment by gahdritz** [comment]
Try increasing the length of the training epoch.

**Comment by Zhang690683220** [comment]
> Try increasing the length of the training epoch.

So this means set --train_epoch_len to a large value?

**Comment by gahdritz** [comment]
Yes. As for the format of the AWS data, you'll need to reformat it slightly. For each chain, you'll want to flatten the hhr and a3m directories, such that the directory for each chain contains both the hhr files and the a3m files for that chain.

**Comment by Zhang690683220** [comment]
Yeah. I've done that. But I found some chains doesn't have all the 4 files(3 .a3m and 1 .hhr).

By the way, I've set the `--train_epoch_len` to 80000 but still not working. If I set it to <=1200, it works but doesn't make sense.

**Comment by gahdritz** [comment]
Could you share your training command?

**Comment by Zhang690683220** [comment]
```
srun python3 train_openfold.py \
/pscratch/sd/b/bz186/openfold/data/pdb_mmcif/mmcif_files \ 
/pscratch/sd/b/bz186/openfold/data/alignment_openfold \ 
/pscratch/sd/b/bz186/openfold/data/pdb_mmcif/mmcif_files \
/pscratch/sd/b/bz186/openfold/data/train_full_output \
2021-10-10 \
--template_release_dates_cache_path=/pscratch/sd/b/bz186/openfold/data/mmcif_cache.json \
--precision=32 \
--gpus=4 \
--replace_sampler_ddp=True \
--seed=42 \
--deepspeed_config_path=/global/homes/b/bz186/openfold/deepspeed_config.json \
--checkpoint_every_epoch \
--obsolete_pdbs_file_path=/pscratch/sd/b/bz186/openfold/data/pdb_mmcif/obsolete.dat \
--train_chain_data_cache_path=/pscratch/sd/b/bz186/openfold/data/chain_data_cache.json \
--train_epoch_len=80000
```

**Comment by gahdritz** [comment]
Is this being run on a single node?

**Comment by Zhang690683220** [comment]
A single node with 4 GPUs , I did it on interactive mode.

**Comment by gahdritz** [comment]
Hm not able to reproduce. Could you share a sample of the directory structure of /pscratch/sd/b/bz186/openfold/data/alignment_openfold?

**Comment by Zhang690683220** [comment]
```
/pscratch/sd/b/bz186/openfold/data/alignment_openfold
    -11as_A
        - bfd_uniclust_hits.a3m
        - mgnify_hits.a3m
        - pdb70_hits.hhr
        - uniref90_hits.a3m
    -11ba_A
        - bfd_uniclust_hits.a3m
        - mgnify_hits.a3m
        - pdb70_hits.hhr
        - uniref90_hits.a3m
    -11ba_B
    -11bg_A
    -11bg_B
    -11gs_A
```
The directory tree is similar as above for all chains ,except some doesn't have all 4 files.

**Comment by gahdritz** [comment]
How about the filter thing?

**Comment by Zhang690683220** [comment]
It prints some of the chain_data_cache_entry like this:
`{'release_date': '2011-02-09', 'seq': 'MSAGKLPEGWVIAPVSTVTTLIRGVTYKKEQAINYLKDDYLPLIRANNIQNGKFDTTDLVFVPKNLVKESQKISPEDIVIAMSSGSKSVVGKSAHQHLPFECSFGAFCGVLRPEKLIFSGFIAHFTKSSLYRNKISSLSAGANINNIKPASFDLINIPIPPLAEQKIIAEKLDTLLAQVDSTKARFEQIPQILKRFRQAVLGGAVNGKLTEKWRNFEPQHSVFKKLNFESILTELRNGLSSKPNESGVGHPILRISSVRAGHVDQNDIRFLECSESELNRHKLQDGDLLFTRYNGSLEFVGVCGLLKKLQHQNLLYPDKLIRARLTKDALPEYIEIFFSSPSARNAMMNCVKTTSGQKGISGKDIKSQVVLLPPVKEQAEIVRRVEQLFAYADTIEKQVNNALARVNNLTQSILAKAFRGELTAQWRAENPDLISGENSAAALLEKIKAERAASGGKKASRKKS', 'resolution': 18.0, 'cluster_size': -1}`

**Comment by gahdritz** [comment]
Could you count how many of your proteins are getting filtered out by that function? I see for example that the resolution of this protein is very high---this one gets filtered for that reason.

**Comment by Zhang690683220** [comment]
The count number of the if block is 26 before it crashes.

**Comment by gahdritz** [comment]
How about the probabilities that come out of the stochastic filter? Are those really small?

**Comment by Zhang690683220** [comment]
I print the `p` right after
```
p = get_stochastic_train_filter_prob(
                        chain_data_cache_entry,
                    )
```
almost all of them are > 0.5
```
p = 1.0
p = 0.609375
p = 0.880859375
p = 0.5
p = 0.5
p = 0.5
p = 0.693359375
p = 0.5
p = 0.5
p = 0.5
p = 0.5
p = 0.6640625
p = 0.822265625
p = 0.001953125
p = 0.5
p = 0.5
p = 0.9140625
p = 0.5
p = 0.5390625
p = 0.52734375
p = 0.5
p = 0.5
p = 0.5
p = 0.51953125
p = 1.0
p = 0.53125
p = 0.5
p = 0.5
p = 0.5
p = 0.5
p = 0.5

```

**Comment by gahdritz** [comment]
Hm so that's not it either. Whatever the issue is, it's probably happening somewhere in that function. Would you mind pinpointing where the samples are disappearing?

**Comment by Zhang690683220** [comment]
I'm trying to do that. But we have some difficulties to understand the code, since we'are only computer science research and do not have required protein knowledge.

**Comment by gahdritz** [comment]
In the reroll() function, could you verify that `len(self._samples) == 1` and also that `torch.sum(dataset_choices) == 0`?

**Comment by Zhang690683220** [comment]
yes, they are. 1 and tensor(0).

**Comment by Zhang690683220** [comment]
since the `self._samples` only has 1 element inside it, I tried to investigate the `self._samples[0]` by doing `print(sum(1 for _ in self._samples[0]))`. This time, it tells me that
```
Traceback (most recent call last):
  File "train_openfold.py", line 548, in <module>
    main(args)
  File "train_openfold.py", line 262, in main
    data_module.setup()
  File "/global/homes/b/bz186/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "/global/u2/b/bz186/openfold/openfold/data/data_modules.py", line 654, in setup
    _roll_at_init=False,
  File "/global/u2/b/bz186/openfold/openfold/data/data_modules.py", line 358, in __init__
    print(sum(1 for _ in self._samples[0]))
  File "/global/u2/b/bz186/openfold/openfold/data/data_modules.py", line 358, in <genexpr>
    print(sum(1 for _ in self._samples[0]))
  File "/global/u2/b/bz186/openfold/openfold/data/data_modules.py", line 334, in looped_samples
    chain_data_cache_entry = chain_data_cache[chain_id]
KeyError: '3wwy_A'
```
But when I check the alignment_dir, this chain does exist:

```
(openfold_venv) bz186@nid001520:~/openfold> ls /pscratch/sd/b/bz186/openfold/data/alignment_openfold | grep 3wwy_A
3wwy_A
(openfold_venv) bz186@nid001520:~/openfold> ls /pscratch/sd/b/bz186/openfold/data/alignment_openfold/3wwy_A
bfd_uniclust_hits.a3m  mgnify_hits.a3m	pdb70_hits.hhr	uniref90_hits.a3m
```

I'm assuming there is something wrong with the file passed by `--train_chain_data_cache_path`. But I did that pre-processing step using the full mmcif dataset downloaded by the script and the PDB40 in the README link. Is there any potential error that could happens given that the AWS dataset is claimed to have ~130,000 chains, however the full mmcif dataset has ~190,000 `.cif` files

**Comment by gahdritz** [comment]
To clarify, `self._samples` contains one infinite iterator for each dataset you're using. Each entry thereof feeds you samples from the corresponding dataset shuffled + filtered in various ways forever.

Yes, it's looking like something is wrong with your train chain data cache. It should contain an entry for every chain for which you have alignments. The total number of .cif files doesn't matter; what controls the size of the dataset objects is the `alignment_dir`. I'll revisit the chain data cache script and see if I can find any errors. In the meantime, you can add a check in that function we were discussing earlier that skips chains that do not appear in your chain data cache.

**Comment by sharish24** [comment]
I also ran into the same problem. I found 395 unique proteins in my `msa_dir` that wasn't in my `mmcif_files` dir and also in my `chain_data_cache.json`. I removed all the chains for the 395 proteins, and the training works for me. I'm guessing there is a difference in the data used to generate the msa.

**Comment by gahdritz** [comment]
Could you verify that every single chain in your `alignment_dir` has a corresponding .mmcif file in the `data_dir`?

**Comment by NZ99** [comment]
Thank you so much for the quick response Gustaf. You're right -- 57 chains appear to be missing. I'm unsure what caused it.

The missing chains are `1erk 3d6s 3rvw 3rvw 3wwy 3wwz 4acq 4ftp 4gbo 4kyu 4pp1 4pp1 4pp1 4roq 4ror 5b7o 5fim 5hbg 5i4g 5l0x 6dfz 6iwl 6l7f 6nuy 6nuy 6nuz 6nuz 6nv0 6nv0 6ors 6qwj 6qwj 6qwj 6qwj 6qwj 6qwj 6qwj 6qwj 6qwj 6qwj 6qwj 6ubg 6ubg 6vig 6vj1 6vmu 6x8v 6xbp 6xdl 6xoe 7ay4 7ayl 7elo 7jnq 7kcd 7ra6 7v7y`.

How do you recommend I proceed? Should I just delete their subdirectories in the template directory?

I doubt there were errors during the download and extraction of the PDB mmcif files. It's also weird that the user above reported 395 missing chains while in my case it's only 57...

**Comment by gahdritz** [comment]
Delete their `alignment_dirs` and rerun. I'll look into what's causing this.

**Comment by NZ99** [comment]
Thank you again Gustaf for the quick response.

I moved all the subdirectories to a separate "missing_mmcif" directory as to make sure no data was lost. I tried rerunning it (same command as before), but I'm now getting a KeyError at line 338 of data_modules.py:

> File "/fsx/openbioml/openfold/openfold/data/data_modules.py", line 338, in looped_samples
>     chain_data_cache_entry = chain_data_cache[chain_id]
> KeyError: '6tif_AAA'

`6tif.cif` is present in the mmcif directory, and `6tif_AAA` is present in the alignment/templates directory with what appear to be all necessary files: `bfd_uniclust_hits.a3m  mgnify_hits.a3m  pdb70_hits.hhr  uniref90_hits.a3m`. However, only `6tif_A` and `6tif_B` are present in `chain_data_cache.json` -- I'll check which chains are missing and move them away too. Will report back tomorrow.

**Comment by gahdritz** [comment]
![image](https://user-images.githubusercontent.com/26167235/181655309-a5038bd8-6257-439f-b725-8a3453605e8f.png)
My `chain_data_cache` has these chains, and I tried parsing my copy of `6tif.cif` and found them there too.

Could you verify that [this file](https://drive.google.com/file/d/18tU1txzDrYug0CBs4S16kEFpd9UM15c6/view?usp=sharing) does not match the copy of `6tif.cif` the installation scripts downloaded for you?

**Comment by NZ99** [comment]
Indeed, the `6tif.cif` file (which I downloaded via the script) does not match yours. I have uploaded mine [here](https://drive.google.com/file/d/15Ayf7yTTzJD4h-AdfomNixCtWDvNfCTs/view?usp=sharing). Still unsure what is causing this, but my `6tif.cif` file only has `A` and `B` chains (just like in the generated `chain_data_cache.json` file. I'm not familiar with `mmcif` files, but the `_audit_conform.dict_version`, in my file, is 5.359 (while in yours it's 5.326). Maybe it has been updated? Indeed if I download the mmCIF file directly off of [PDB](https://www.rcsb.org/structure/6TIF) the file matches mine (dict_version 5.359, only chains `A` and `B` present).

**Comment by gahdritz** [comment]
Sigh...

The way the data is set up assumes that PDB .cif files don't change over time. I'll need to do some thinking to figure out the best way to address this. I might end up having to upload my set of .cif files to RODA.

Thanks for running these diagnostics!

**Comment by NZ99** [comment]
Nah, thank _you_ for OpenFold! :)

I checked if any other chains had the same issue, but none appear to apart from the aforementioned `6tif_AAA`. Removing it from the alignment directory seems to fix the issue, but I soon run into another. I don't think it's related -- please let me know if you'd prefer me opening a separate issue.

I'm first getting a warning `UserWarning: One of given dataloaders is None and it will be skipped.`

I'm then getting several more warnings about exact sequences missing. An example is the following:

> WARNING:root:The exact sequence MTTPRRALIVIDVQNEYVTGDLPIEYPDVQSSLANIARAMDAARAAGVPVVIVQNFAPAGSPLFARGSNGAELHPVVSERARDHYVEKSLPSAFTGTDLAGWLAARQIDTLTVTGYMTHNADASTINHAVHSGLAVEFLHDATGSVPYENSAGFASAEEIHRVFSVVLQSRFAAVASTDEWIAAVQGGTPLA was not found in 3oqp_A. Realigning the template to the actual sequence.

Finally, I get a `RuntimeError: expected scalar type BFloat16 but found Half` (not sure if related to #180):

> Traceback (most recent call last):
  File "/fsx/openbioml/openfold/train_openfold.py", line 104, in training_step
    outputs = self(batch)
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/openbioml/openfold/train_openfold.py", line 67, in forward
    return self.model(batch)
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/openbioml/openfold/openfold/model/model.py", line 510, in forward
    _recycle=(num_iters > 1)
  File "/fsx/openbioml/openfold/openfold/model/model.py", line 243, in iteration
    inplace_safe=inplace_safe,
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/openbioml/openfold/openfold/model/embedders.py", line 116, in forward
    tf_emb_i = self.linear_tf_z_i(tf)
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  RuntimeError: expected scalar type BFloat16 but found Half

A cursory google search leards to https://discuss.pytorch.org/t/mixed-precision-training-on-cuda-with-bfloat16/156248, so I tried re-running with fp16 rather than bfloat16, and apart from the same warnings I now get a `ValueError("Unsupported datatype")`:

> File "/fsx/openbioml/openfold/train_openfold.py", line 104, in training_step
    outputs = self(batch)
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/openbioml/openfold/train_openfold.py", line 67, in forward
    return self.model(batch)
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/openbioml/openfold/openfold/model/model.py", line 510, in forward
    _recycle=(num_iters > 1)
  File "/fsx/openbioml/openfold/openfold/model/model.py", line 367, in iteration
    _mask_trans=self.config._mask_trans,
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/openbioml/openfold/openfold/model/evoformer.py", line 996, in forward
    m, z = checkpoint_fn(b, m, z)
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 743, in checkpoint
    CheckpointFunction.apply(function, all_outputs, *args)
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 582, in forward
    outputs = run_function(*inputs_cuda)
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/openbioml/openfold/openfold/model/evoformer.py", line 519, in forward
    self.ckpt if torch.is_grad_enabled() else False,
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/openbioml/openfold/openfold/model/msa.py", line 284, in forward
    flash_mask=mask,
  File "/fsx/openbioml/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/openbioml/openfold/openfold/model/primitives.py", line 488, in forward
    o = attention_core(q, k, v, *((biases + [None] * 2)[:2]))
  File "/fsx/openbioml/openfold/openfold/utils/kernel/attention_core.py", line 32, in forward
    raise ValueError("Unsupported datatype")

Thinking that maybe something went wrong with flash attention's installation? Any tips? I would also greatly appreciate if you could share the DeepSpeed config you used for the reproduction run you reported. I'm running this on 64 A100s, so the setup should be similar to your one (which IIRC was on 45 A100s). All of this is for an open-source project that I would love to chat with you about at some point! :)

**Comment by gahdritz** [comment]
The "exact sequence" warning is expected and is nothing to worry about. As for the precision thing, could we move this to #180? I'm pretty sure it's the same thing.

**Comment by NZ99** [comment]
I wonder if the issue is with the `.pdb` filenames? Here is what my `distillation_data_dir` looks like:
> A0A009EX06_model_5_unrelaxed.pdb
> A0A009EY75_model_5_unrelaxed.pdb
> A0A009FAV8_model_5_unrelaxed.pdb
> A0A009GC30_model_5_unrelaxed.pdb
> A0A009GC83_model_5_unrelaxed.pdb
> A0A009H2D3_model_5_unrelaxed.pdb
> A0A009H847_model_5_unrelaxed.pdb
> A0A009HRS4_model_5_unrelaxed.pdb
> A0A009IPF9_model_5_unrelaxed.pdb
> A0A009J662_model_5_unrelaxed.pdb

Those filenames also appear unmodified in the generated `chain_data_cache` json file. However, my `distillation_alignment_dir` looks like this:

> A0A009EX06
> A0A009EY75
> A0A009FAV8
> A0A009GC30
> A0A009GC83
> A0A009H2D3
> A0A009H847
> A0A009HRS4
> A0A009IPF9
> A0A009J662 

Do you think this could indeed be the issue? In this case I guess the fix would be to simply renaming each `.pdb` file (removing `_model_5_unrelaxed`) and re-generating the `distillation_chain_data_cache` json file.

Since this is related to distillation, please let me know if you'd like me to move this discussion to #187.
