### ISSUE TITLE
Getting a CUBLAS_STATUS_INVALID_VALUE when using CUDA 11.3 and pytorch 1.12

### ISSUE THREAD

**Issue by mgalardini** [aqlaboratory/openfold#144]
Hi, I'm trying to run openfold on our GeForce RTX 3090. Because of a CUDA capability sm_86 warning message I decided to upgrade both pytorch and the cuda toolkit requirements in the `environment.yml` file:

```
[...]
pytorch::pytorch=1.12.*
[...]
conda-forge::cudatoolkit==11.3.*
conda-forge::cudatoolkit-dev==11.3.*
[...]
```

Both the `install_third_party_dependencies.sh` and `setup.py install` complete without error, but then I get the following error when running this command:

```
$ python3 run_pretrained_openfold.py seq/ data/pdb_mmcif/mmcif_files/ --use_precomputed_alignments aln --output_dir ~/fast/marco/small/20220628_openfold --cpus 24 --model_device "cuda:0" >run.err 2>&1

INFO:run_pretrained_openfold.py:Using precomputed alignments at aln...
INFO:run_pretrained_openfold.py:Successfully loaded JAX parameters at openfold/resources/params/params_model_1.npz...
INFO:run_pretrained_openfold.py:Running inference for Ti9_00003...
Traceback (most recent call last):
  File "run_pretrained_openfold.py", line 481, in <module>
    main(args)
  File "run_pretrained_openfold.py", line 351, in main
    out = run_model(model, working_batch, tag, args)
  File "run_pretrained_openfold.py", line 100, in run_model
    out = model(batch)
  File "/home/marco/fast/software/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fast-storage/software/openfold/openfold/model/model.py", line 503, in forward
    _recycle=(num_iters > 1)
  File "/fast-storage/software/openfold/openfold/model/model.py", line 238, in iteration
    inplace_safe=inplace_safe,
  File "/home/marco/fast/software/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fast-storage/software/openfold/openfold/model/embedders.py", line 116, in forward
    tf_emb_i = self.linear_tf_z_i(tf)
  File "/home/marco/fast/software/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/marco/fast/software/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

I have tried googling around but had no luck. Anything you think I might be missing to use CUDA 11.3? Thanks for this amazing piece of software.

**Comment by gahdritz** [comment]
I'm running torch==10.1+cu11.3 on a system with CUDA version 11.4 and CUDA driver version 470.82.01. That works with my A100s.

**Comment by mgalardini** [comment]
Thanks for the suggestion: I changed the `environment.yml` file to use `pytorch=1.10.*` and cuda 11.3 and now I get a different error (`CUBLAS_STATUS_NOT_SUPPORTED`)

```
INFO:run_pretrained_openfold.py:Using precomputed alignments at aln...
INFO:run_pretrained_openfold.py:Successfully loaded JAX parameters at openfold/resources/params/params_model_1.npz...
INFO:run_pretrained_openfold.py:Running inference for Ti9_00006...
Traceback (most recent call last):
  File "run_pretrained_openfold.py", line 481, in <module>
    main(args)
  File "run_pretrained_openfold.py", line 351, in main
    out = run_model(model, working_batch, tag, args)
  File "run_pretrained_openfold.py", line 100, in run_model
    out = model(batch)
  File "/home/marco/fast/software/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fast-storage/software/openfold/openfold/model/model.py", line 503, in forward
    _recycle=(num_iters > 1)
  File "/fast-storage/software/openfold/openfold/model/model.py", line 238, in iteration
    inplace_safe=inplace_safe,
  File "/home/marco/fast/software/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fast-storage/software/openfold/openfold/model/embedders.py", line 116, in forward
    tf_emb_i = self.linear_tf_z_i(tf)
  File "/home/marco/fast/software/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/marco/fast/software/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/marco/fast/software/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

I'll try again with CUDA 11.4 just to be sure

**Comment by A-BigBao** [comment]
> I'm running torch==1.10+cu11.3 on a system with CUDA version 11.3/4 and CUDA driver version 470.82.01. That works with my A100s.

Would you mind sharing how you modify the install files and steps? Many thanks!

**Comment by gahdritz** [comment]
To get my specific installation, run the install scripts and then, on top of that, run

`conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge`

**Comment by mgalardini** [comment]
Ah yes this worked, thanks a lot! In case it's useful for anyone else reading this, the above `conda install` command must be run after the `python3 setup.py install` step

**Comment by gahdritz** [comment]
Really? What happens if you run `setup.py` afterwards?

**Comment by mgalardini** [comment]
I was getting an error related to a mismatch in CUDA versions used to compile pytorch. I don't have the error message saved unfortunately
