### ISSUE TITLE
ModuleNotFoundError: No module named 'flash_attn'

### ISSUE THREAD

**Issue by lucajovine** [aqlaboratory/openfold#151]
After last update (commit 9225f8725b53d19643d1469a57f7d7baea3c0625):

```
> python3 run_pretrained_openfold.py
Traceback (most recent call last):
  File "run_pretrained_openfold.py", line 49, in <module>
    from openfold.config import model_config, NUM_RES
  File "/usr/local/openfold/openfold/openfold/__init__.py", line 1, in <module>
    from . import model
  File "/usr/local/openfold/openfold/openfold/model/__init__.py", line 11, in <module>
    _modules = [(m, importlib.import_module("." + m, __name__)) for m in __all__]
  File "/usr/local/openfold/openfold/openfold/model/__init__.py", line 11, in <listcomp>
    _modules = [(m, importlib.import_module("." + m, __name__)) for m in __all__]
  File "/usr/local/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/openfold/openfold/openfold/model/evoformer.py", line 22, in <module>
    from openfold.model.primitives import Linear, LayerNorm
  File "/usr/local/openfold/openfold/openfold/model/primitives.py", line 21, in <module>
    from flash_attn.bert_padding import unpad_input, pad_input
ModuleNotFoundError: No module named 'flash_attn'
```

**Comment by lucajovine** [comment]
...which originates from this scripts/install_third_party_dependencies.sh:

```
(...)
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/usr/local/openfold/openfold/lib/conda/envs/openfold_venv/bin/python', '-m', 'pip', 'install', '-U', '-r', '/usr/local/openfold/openfold/condaenv.1hlsitm4.requirements.txt']
Pip subprocess output:
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/HazyResearch/flash-attention.git (from -r /usr/local/openfold/openfold/condaenv.1hlsitm4.requirements.txt (line 13))
  Cloning https://github.com/HazyResearch/flash-attention.git to /tmp/pip-req-build-hmm5sk9_
  Resolved https://github.com/HazyResearch/flash-attention.git to commit 1bbebccc0a99068a93820c17338ab408609ef6ac
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/HazyResearch/flash-attention.git /tmp/pip-req-build-hmm5sk9_
  Running command git submodule update --init --recursive -q
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-hmm5sk9_/setup.py", line 110, in <module>
          raise RuntimeError("FlashAttention is only supported on CUDA 11")
      RuntimeError: FlashAttention is only supported on CUDA 11


      torch.__version__  = 1.12.0


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

**Comment by lucajovine** [comment]
So I guess cudatoolkit-11.x should be installed rather than cudatoolkit-10.2.89 ?

**Comment by gahdritz** [comment]
Fixed in `5cf9987`.

**Comment by lucajovine** [comment]
Absolutely, no problem! But now I am getting this though:

```
(...)
Executing transaction: | By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
ERROR conda.core.link:_execute(730): An error occurred while installing package 'conda-forge::cudatoolkit-dev-11.3.1-py37h5e8e339_0'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-11.3.1-py37h5e8e339_0
location of failed script: /usr/local/openfold/openfold/lib/conda/envs/openfold_venv/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Running Post installation
downloading https://developer.download.nvidia.com/compute/cuda/11.3.1/local_installers/cuda_11.3.1_465.19.01_linux.run to /usr/local/openfold/openfold/lib/conda/envs/openfold_venv/pkgs/cudatoolkit-dev/cuda_11.3.1_465.19.01_linux.run
Extracting on Linux

stderr: Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/usr/local/openfold/openfold/lib/conda/envs/openfold_venv/bin/cudatoolkit-dev-post-install.py", line 216, in <module>
    _main()
  File "/usr/local/openfold/openfold/lib/conda/envs/openfold_venv/bin/cudatoolkit-dev-post-install.py", line 212, in _main
    extractor.extract()
  File "/usr/local/openfold/openfold/lib/conda/envs/openfold_venv/bin/cudatoolkit-dev-post-install.py", line 124, in extract
    subprocess.run(cmd, env=os.environ.copy(), check=True)
  File "/usr/local/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/openfold/openfold/lib/conda/envs/openfold_venv/pkgs/cudatoolkit-dev/cuda_11.3.1_465.19.01_linux.run', '--silent', '--toolkit', '--toolkitpath=/tmp/tmp1bn_2kjs', '--override']' returned non-zero exit status 139.

return code: 1

()

/usr/local/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages /usr/local/openfold/openfold
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: simtk/openmm/app/topology.py
|===================================================================
|--- simtk.orig/openmm/app/topology.py
|+++ simtk/openmm/app/topology.py
--------------------------
File to patch:
```

**Comment by lucajovine** [comment]
I am confused by the segmentation fault, as I have 256 GB RAM on this machine and never seen it before...

**Comment by gahdritz** [comment]
Hm I've never seen that one before either. What version of CUDA do you have?

**Comment by lucajovine** [comment]
```> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Sep_13_19:13:29_PDT_2021
Cuda compilation tools, release 11.5, V11.5.50
Build cuda_11.5.r11.5/compiler.30411180_0
```

**Comment by lucajovine** [comment]
Yes, like this the installation completed, apart from minor warnings such as:

```/usr/local/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.5) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
/usr/local/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.5
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
  ```

Now running a test inference to confirm...

**Comment by lucajovine** [comment]
Inference ran fine. I guess we can close this?

**Comment by lucajovine** [comment]
Alright, thanks again!
