### ISSUE TITLE
ERROR: Could find neither hhm_db nor a3m_db!

### ISSUE THREAD

**Issue by liweiqing1997** [aqlaboratory/openfold#231]
May I ask why this error occurs, I have confirmed that the relevant database and file paths are correct as required. However, using docker does not have this error when the args file path parameters are the same.

jackhmmer_uniref90_runner done
jackhmmer_mgnify_runner done
ERROR:root:HHblits failed. HHblits stderr begin:
ERROR:root:- 16:09:56.345 ERROR: Could find neither hhm_db nor a3m_db!
ERROR:root:HHblits stderr end
Traceback (most recent call last):
  File "run_pretrained_openfold.py", line 455, in <module>
    main(args)
  File "run_pretrained_openfold.py", line 283, in main
    precompute_alignments(tags, seqs, alignment_dir, args)
  File "run_pretrained_openfold.py", line 77, in precompute_alignments
    tmp_fasta_path, local_alignment_dir
  File "/data/lwq/openfold-1.0.0/openfold/data/data_pipeline.py", line 452, in run
    hhblits_bfd_uniclust_result = (
  File "/data/lwq/openfold-1.0.0/openfold/data/tools/hhblits.py", line 162, in query
    % (stdout.decode("utf-8"), stderr[:500_000].decode("utf-8"))
RuntimeError: HHblits failed
stdout:

stderr:
- 16:09:56.345 ERROR: Could find neither hhm_db nor a3m_db!

**Comment by yamule** [comment]
It may be a permissions issue.
https://github.com/deepmind/alphafold/issues/202

**Comment by liweiqing1997** [comment]
> It may be a permissions issue. [deepmind/alphafold#202](https://github.com/deepmind/alphafold/issues/202)

That's true, thanks
