### ISSUE TITLE
Alignment error

### ISSUE THREAD

**Issue by Ottovonxu** [aqlaboratory/openfold#256]
Hi

I ran the following scripts and get the error in alignment.

    python3 scripts/precompute_alignments.py data/pdb_mmcif/mmcif_files/ data/alignment/ \
        --uniref90_database_path data/uniref90/uniref90.fasta \
        --mgnify_database_path data/mgnify/mgy_clusters_2018_12.fa \
        --pdb70_database_path data/pdb70/pdb70 \
        --uniclust30_database_path data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
        --bfd_database_path data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
        --cpus 16 \
        --jackhmmer_binary_path lib/conda/envs/openfold_venv/bin/jackhmmer \
        --hhblits_binary_path lib/conda/envs/openfold_venv/bin/hhblits \
        --hhsearch_binary_path lib/conda/envs/openfold_venv/bin/hhsearch \
        --kalign_binary_path lib/conda/envs/openfold_venv/bin/kalign

Here is the error log:

    ERROR:root:- 09:17:56.463 ERROR: Error in /opt/conda/conda-bld/hhsuite_1645696999782/work/src/hhalignment.cpp:3539: MergeMasterSlave:
    ERROR:root:- 09:17:56.463 ERROR:        did not find 145 match states in sequence 1 of tr|A0A1D1YLJ1|A0A1D1YLJ1_9ARAE. Sequence:
    ERROR:root:GYKAPELTKMKDAGKESDIYSLGVIFLEMVTRKDTNSDFLPTWDLHLSNSLKNPVFDGKISEMISHGLLRQSREQNCITGEGLLMFLQLAIACRSPSPRLRPDIKQVLGKLEEIELWKLPNQFGGDRLPNRG
    ERROR:root:HHblits stderr end
    WARNING:root:Failed to run alignments for 7avy_A. Skipping...
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "scripts/precompute_alignments.py", line 40, in run_seq_group_alignments
        fasta_path, alignment_dir
      File "/scratch1/zx22/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/openfold-1.0.0-py3.7-linux-x86_64.egg/openfold/data/data_pipeline.py", line 485, in run
        self.hhblits_bfd_uniclust_runner.query(fasta_path)
      File "/scratch1/zx22/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/openfold-1.0.0-py3.7-linux-x86_64.egg/openfold/data/tools/hhblits.py", line 162, in query
        % (stdout.decode("utf-8"), stderr[:500_000].decode("utf-8"))
    RuntimeError: HHblits failed
    stdout:
    stderr:

Could you help me with it? Thanks!

**Comment by gahdritz** [comment]
Not sure about this one. I recommend making an issue on the HHSuite GitHub page.

**Comment by gahdritz** [comment]
(didn't mean to close)
