### ISSUE TITLE
ModuleNotFoundError: No module named 'attn_core_inplace_cuda'

### ISSUE THREAD

**Issue by SimonKitSangChu** [aqlaboratory/openfold#259]
No module named `attn_core_inplace_cuda` was found during inference on A100. Preinstalled CUDA 11.6 outside of conda. 

```
Traceback (most recent call last):
  File "run_pretrained_openfold.py", line 21, in <module>
    from openfold.utils.script_utils import load_models_from_command_line, parse_fasta, run_model, prep_output, \
  File "/scratch/user/openfold/openfold/utils/script_utils.py", line 10, in <module>
    from openfold.model.model import AlphaFold
  File "/scratch/user/openfold/openfold/model/model.py", line 21, in <module>
    from openfold.model.embedders import (
  File "/scratch/user/openfold/openfold/model/embedders.py", line 20, in <module>
    from openfold.model.primitives import Linear, LayerNorm
  File "/scratch/user/openfold/openfold/model/primitives.py", line 37, in <module>
    from openfold.utils.kernel.attention_core import attention_core
  File "/scratch/user/openfold/openfold/utils/kernel/attention_core.py", line 20, in <module>
    attn_core_inplace_cuda = importlib.import_module("attn_core_inplace_cuda")
  File "/scratch/user/openfold/lib/conda/envs/openfold_venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'attn_core_inplace_cuda'
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

**Comment by gahdritz** [comment]
Did you run setup.py?

**Comment by Kongjh** [comment]
Have u fix this issue？ I got the same error

**Comment by pengtb** [comment]
> Run scripts/install_third_party_dependencies.sh to configure kernels and folding resources.
exec the script then everthing is ok

**Comment by Tom0515Lt** [comment]
I got the same question.How to deal?
