### ISSUE TITLE
Problem on scripts/install_third_party_dependencies.sh

### ISSUE THREAD

**Issue by data-weirdo** [aqlaboratory/openfold#262]
When it comes to installation on Linux, 
`scripts/install_third_party_dependencies.sh`, which is the very first code that I should execute, does not work correctly.

It shows

```
Pip subprocess error:
 
failed

CondaEnvException: Pip failed
```

Thereafter, all the codes are useless.
Can you tell me how to solve this problem on the most recent version? 

---

```
conda update -n base -c defaults conda
```
which is suggested as a solution does not work.

**Comment by anpanche** [comment]
I am also facing same problem. Are there any requirements to be fulfilled for installation of openfold? Is GPU necessary?

**Comment by gahdritz** [comment]
Hm I just tried reinstalling OpenFold from scratch and am unable to reproduce this behavior. Could you share:

1. The full output of the command
2. Details about your environment (incl. CUDA installation, etc.)

**Comment by gahdritz** [comment]
@anpanche you too.

**Comment by fglaser** [comment]
Same problem here:

mamba env create -n openfold_env -f environment.yml
Channels:
 - conda-forge
 - bioconda
 - pytorch
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 24.3.0
    latest version: 24.5.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: - By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/home/fabian/miniforge3/envs/openfold_env/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/fabian/openfold/condaenv.v3nskj_k.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting git+https://github.com/NVIDIA/dllogger.git (from -r /home/fabian/openfold/condaenv.v3nskj_k.requirements.txt (line 3))
  Cloning https://github.com/NVIDIA/dllogger.git to /tmp/pip-req-build-5qi5j6us
  Resolved https://github.com/NVIDIA/dllogger.git to commit 0540a43971f4a8a16693a9de9de73c1072020769
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting git+https://github.com/Dao-AILab/flash-attention.git@5b838a8 (from -r /home/fabian/openfold/condaenv.v3nskj_k.requirements.txt (line 4))
  Cloning https://github.com/Dao-AILab/flash-attention.git (to revision 5b838a8) to /tmp/pip-req-build-coan6uef
  Resolved https://github.com/Dao-AILab/flash-attention.git to commit 5b838a8
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA/dllogger.git /tmp/pip-req-build-5qi5j6us
  Running command git clone --filter=blob:none --quiet https://github.com/Dao-AILab/flash-attention.git /tmp/pip-req-build-coan6uef
  WARNING: Did not find branch or tag '5b838a8', assuming revision or ref.
  Running command git checkout -q 5b838a8
  Running command git submodule update --init --recursive -q
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-coan6uef/setup.py", line 105, in <module>
          raise_if_cuda_home_none("flash_attn")
        File "/tmp/pip-req-build-coan6uef/setup.py", line 55, in raise_if_cuda_home_none
          raise RuntimeError(
      RuntimeError: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
      
      
      torch.__version__  = 1.12.1
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
