### ISSUE TITLE
ValueError: Could not find HHBlits database path/uniclust30_2018_08

### ISSUE THREAD

**Issue by ArsLeicholt** [aqlaboratory/openfold#281]
Hey guys

Great work! I am trying to get OpenFold running on our cluster and having problems with hhblits on uniclust30. I adapted the longer paths to just "path" for privacy reasons. Help would be much appreciated. Tried out reinstalling the uniclust30 database already and triple-checked all the paths.

**ERROR Message**

`INFO:/path/run_pretrained_openfold.py:Generating alignments for goddard...
ERROR:root:Could not find HHBlits database path/uniclust30_2018_08
Traceback (most recent call last):
  File "path/run_pretrained_openfold.py", line 451, in <module>
    main(args)
  File "path/run_pretrained_openfold.py", line 284, in main
    precompute_alignments(tags, seqs, alignment_dir, args)
  File "path/run_pretrained_openfold.py", line 66, in precompute_alignments
    alignment_runner = data_pipeline.AlignmentRunner(
  File "path/data_pipeline.py", line 377, in __init__
    self.hhblits_bfd_uniclust_runner = hhblits.HHBlits(
  File "pathhhblits.py", line 86, in __init__
    raise ValueError(
ValueError: Could not find HHBlits database path/uniclust30_2018_08`

**The uniclust30_2018_08 directory contains the 13 files from the hhblits_hmm** 

`uniclust30_2018_08.cs219        uniclust30_2018_08_a3m.ffdata   uniclust30_2018_08_a3m_db        uniclust30_2018_08_cs219.ffdata   uniclust30_2018_08_hhm.ffdata   uniclust30_2018_08_hhm_db        uniclust30_2018_08_md5sum
uniclust30_2018_08.cs219.sizes  uniclust30_2018_08_a3m.ffindex  uniclust30_2018_08_a3m_db.index  uniclust30_2018_08_cs219.ffindex  uniclust30_2018_08_hhm.ffindex  uniclust30_2018_08_hhm_db.index`

**Complete slurm script**

`#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks 4
#SBATCH --cpus-per-task 8
#SBATCH --mem=80G
#SBATCH --partition=gpu2080
#SBATCH --gres=gpu:1
#SBATCH --time=24:00:00
#SBATCH --job-name=openfold_test
#SBATCH --mail-type=ALL

module --force purge

ml palma/2021a
ml gompi/2021a
ml OpenFold/1.0.0-CUDA-11.3.1

wait

 run_pretrained_openfold.py \
    /path/fasta/ \
    /path/pdb_mmcif/mmcif_files \
    --uniref90_database_path /path/uniref90.fasta \
    --mgnify_database_path /path/small_bfd/bfd-first_non_consensus_sequences.fasta \
    --pdb70_database_path /path/data/alphafold/pdb70 \
    --uniclust30_database_path /path/uniclust30_2018_08  \
    --output_dir path/results/ \
    --bfd_database_path=/path/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
    --model_device "cuda:0" \
    --jackhmmer_binary_path /path/jackhmmer.py \
    --hhblits_binary_path /path/hhblits.py \
    --hhsearch_binary_path /path/hhsearch.py \
    --kalign_binary_path /path/kalign.py \
    --config_preset "model_1_ptm" \
    --openfold_checkpoint_path /path/finetuning_ptm_2.pt

#ENV`

**Comment by tsbartle** [comment]
I am receiving the same error in a similar environment.

**Comment by vetmax7** [comment]
Hello!

Could you find solutions?

**Comment by 1999caozhigang** [comment]
![4bf8d1dd8f02297deb748626fa1a392](https://github.com/user-attachments/assets/a9b33a9b-c67b-425d-b46c-367469d4a942)
please!!!

**Comment by vetmax7** [comment]
I could only run my script if I removed ''--uniref30_database_path". Also I write full path for "--bfd_database_path": "bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt".

**Comment by 1999caozhigang** [comment]
> 我只有删除“--uniref30_database_path”才能运行我的脚本。此外，我还为“--bfd_database_path”写入了完整路径：“bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt”。

Can you tell me what this problem is? Is it a problem with the database address pointing to?

**Comment by zhangyichen534** [comment]
我把--bfd_database_path的路径删除了，代码好像会使用他默认的小型数据库进行MSA的推理，运行成功了
