### ISSUE TITLE
unit-tests not passing

### ISSUE THREAD

**Issue by Pellarin** [aqlaboratory/openfold#305]
Hello, it is not clear to me what cause created these errors during `scripts/run_unit_tests.sh`

```
s.....................s.Es.sss.ss....sssssss.sss....sssssFs.s.s.s.s...s.s..ss...ss.s.s.E
======================================================================
ERROR: test_shape (tests.test_evoformer.TestExtraMSAStack)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rpellarin/openfold/openfold/tests/test_evoformer.py", line 221, in test_shape
    z = es(m, z, chunk_size=4, msa_mask=msa_mask, pair_mask=pair_mask)
  File "/home/rpellarin/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rpellarin/openfold/openfold/openfold/model/evoformer.py", line 1006, in forward
    m, z = b(m, z)
  File "/home/rpellarin/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rpellarin/openfold/openfold/openfold/model/evoformer.py", line 525, in forward
    self.ckpt if torch.is_grad_enabled() else False,
  File "/home/rpellarin/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rpellarin/openfold/openfold/openfold/model/msa.py", line 273, in forward
    flash_mask=mask,
  File "/home/rpellarin/openfold/openfold/openfold/model/msa.py", line 125, in _chunk
    no_batch_dims=len(m.shape[:-2])
  File "/home/rpellarin/openfold/openfold/openfold/utils/chunk_utils.py", line 299, in chunk_layer
    output_chunk = layer(**chunks)
  File "/home/rpellarin/openfold/openfold/openfold/model/msa.py", line 108, in fn
    flash_mask=flash_mask,
  File "/home/rpellarin/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rpellarin/openfold/openfold/openfold/model/primitives.py", line 492, in forward
    o = attention_core(q, k, v, *((biases + [None] * 2)[:2]))
  File "/home/rpellarin/openfold/openfold/openfold/utils/kernel/attention_core.py", line 50, in forward
    attention_logits.shape[-1],
RuntimeError: input must be a CUDA tensor

======================================================================
ERROR: tests.test_utils (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_utils
Traceback (most recent call last):
  File "/home/rpellarin/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/rpellarin/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/rpellarin/openfold/openfold/tests/test_utils.py", line 26, in <module>
    from openfold.utils.tensor_utils import chunk_layer, _chunk_slice
ImportError: cannot import name 'chunk_layer' from 'openfold.utils.tensor_utils' (/home/rpellarin/openfold/openfold/openfold/utils/tensor_utils.py)


======================================================================
FAIL: test_dry_run (tests.test_model.TestModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rpellarin/openfold/openfold/tests/test_model.py", line 77, in test_dry_run
    out = model(batch)
  File "/home/rpellarin/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rpellarin/openfold/openfold/openfold/model/model.py", line 515, in forward
    _recycle=(num_iters > 1)
  File "/home/rpellarin/openfold/openfold/openfold/model/model.py", line 319, in iteration
    inplace_safe=inplace_safe,
  File "/home/rpellarin/openfold/openfold/openfold/model/model.py", line 174, in embed_templates
    _mask_trans=self.config._mask_trans,
  File "/home/rpellarin/openfold/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rpellarin/openfold/openfold/openfold/model/template.py", line 389, in forward
    assert(not self.training)
AssertionError

----------------------------------------------------------------------
Ran 88 tests in 12.306s

FAILED (failures=1, errors=2, skipped=36)

Test(s) failed. Make sure you've installed all Python dependencies.
```

**Comment by gahdritz** [comment]
I had let these get a little rusty. These issues should now be resolved.
