### ISSUE TITLE
Unexpected key(s) in state_dict: "aux_heads.tm.linear.weight", "aux_heads.tm.linear.bias"

### ISSUE THREAD

**Issue by srayan00** [aqlaboratory/openfold#319]
I am trying to run inference using OpenFold and I found that finetining_ptm_2.pt was missing in openfold/resources/openfold_params. I found a similar file on [hugging faces ](https://huggingface.co/nz/OpenFold/blob/1c97ae6b3b5482adac17888bbf1d547f81f8a888/README.md) and used their file. But I am getting the following error :

`Traceback (most recent call last):
  File "/opt/openfold/run_pretrained_openfold.py", line 391, in <module>
    main(args)
  File "/opt/openfold/run_pretrained_openfold.py", line 203, in main
    for model, output_directory in model_generator:
  File "/opt/openfold/openfold/utils/script_utils.py", line 101, in load_models_from_command_line
    model.load_state_dict(d)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for AlphaFold:
	Unexpected key(s) in state_dict: "aux_heads.tm.linear.weight", "aux_heads.tm.linear.bias". 
`

The huggingfaces file is from 11 months ago. So, is there a more recent file that I can use or should I remove those keys altogether?

**Comment by roivant-matts** [comment]
you may need to add the config_preset command. In the README this is used in the non-docker example, but not the docker example and resolved this issue in my use.
--config_preset "model_1_ptm" \

**Comment by jensenlijx** [comment]
I don't use docker to run the code, but get the same issue, and try the config_preset config, it doesn't work. Have somebody solved this problem? please give me a hand.

**Comment by jensenlijx** [comment]
I found that using the "finetuning_ptm_1.pt" to replace "finetining_ptm_2.pt" can work well.

**Comment by vetmax7** [comment]
Hello!

I' ve got such error `RuntimeError: Error(s) in loading state_dict for AlphaFold:                                                                     Missing key(s) in state_dict: "aux_heads.tm.linear.weight", "aux_heads.tm.linear.bias".` 
when I tried to use my own checkpoint after train OpenFold.

` --openfold_checkpoint_path /checkpoints/14my.ckpt`  for running `run_pretrained_openfold.py` script

Who can explain me please how to solve this problem?
