### ISSUE TITLE
Soloseq inference - can't fold using ESM-1b alone 

### ISSUE THREAD

**Issue by amardeepranu** [aqlaboratory/openfold#409]
In the README it states that template finding for SoloSeq will be skipped if no tools or dbs are passed, and the fold will happen using ESM alone. However I get multiple errors when running the following command:

```
python openfold/run_pretrained_openfold.py \
    meth_fastas \
    openfold/data/pdb_mmcif/mmcif_files \
    --output_dir results \
    --model_device "cuda:0" \
    --config_preset "seq_model_esm1b_ptm" \
    --openfold_checkpoint_path openfold/openfold/resources/openfold_soloseq_params/seq_model_esm1b_ptm.pt
```

1. If the mmcif_files are not downloaded it fails if they aren't downloaded, I had to download them to get past this.
2. Removing all args related to tools and db like above, I still get a HHSearch error:

```
INFO:/root/openfold/openfold/openfold/utils/script_utils.py:Loaded OpenFold parameters at openfold/openfold/resources/openfold_soloseq_params/seq_model_esm1b_ptm.pt...
INFO:/root/openfold/openfold/run_pretrained_openfold.py:Generating alignments for MGYG000000044_01310...
Traceback (most recent call last):
  File "/root/openfold/openfold/run_pretrained_openfold.py", line 470, in <module>
    main(args)
  File "/root/openfold/openfold/run_pretrained_openfold.py", line 275, in main
    precompute_alignments(tags, seqs, alignment_dir, args)
  File "/root/openfold/openfold/run_pretrained_openfold.py", line 80, in precompute_alignments
    template_searcher = hhsearch.HHSearch(
  File "/root/openfold/openfold/openfold/data/tools/hhsearch.py", line 58, in __init__
    if not glob.glob(database_path + "_*"):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

It still seems to be attempting to generate alignments. Is this an error? Do I need to specify another flag to skip every tool + alignment and just use ESM based folding?

Thank you.

**Comment by jnwei** [comment]
Hi @amardeepranu , thanks for your interest in Soloseq.

Could you try generating the embeddings first using:
`python scripts/precompute_embeddings.py fasta_dir/ embeddings_output_dir/`

And then using the same `run_pretrained_openfold.py` command, but with `--use_precomputed_alignments=embeddings_output_dir`

**Comment by jnwei** [comment]
There are a separate set of weights used for soloseq, which were defined in your earlier command by this argument: `    --openfold_checkpoint_path openfold/openfold/resources/openfold_soloseq_params/seq_model_esm1b_ptm.pt`

Judging by the `bash: line 6: --output_dir: command not found` message, perhaps there's a whitespace/ newline character issue in the command?

**Comment by jnwei** [comment]
You will need to provide a directory for the `--template_mmcif_dir`. Despite the required flag, templates are not necessary for folding predictions.

If your precomputed alignments directory does not contain any alignments for templates (e.g. it only contains the pre-computed ESM embeddings), then template structures will not be used for creating the prediction.

In the future, we may refactor the inference script so that the soloseq mode does not require a `template_mmcif_dir` if the template-based prediction path is not used to help avoid this confusion.

**Comment by vaclavhanzl** [comment]
Note that the directory cannot be empty so if you want to use no templates at all, at the moment you still need to at least fake one with something like `touch empty.cif`.

**Comment by vaclavhanzl** [comment]
@zzzendurance Did you try to make one fake cif file in that empty directory using touch as I propose above? Completely empty file is fine for this.

**Comment by zzzendurance** [comment]
@vaclavhanzl 

Thank you very much for pointing that out! I have resolved the issue with data/pdb_mmcif/mmcif_files/ following your suggestion.

While running the code, I also encountered another error:
ValueError: Amber minimization can only be performed on proteins with well-defined residues. This protein contains at least one residue with no atoms.
I fixed it by adding the --skip_relaxation flag to the original command. After doing this, the predicted PDB files were successfully generated.

I opened these PDB files in a text editor to take a quick look, but due to my limited experience, I'm not sure whether the generated structures are correct. The content looks roughly like this:

` REMARK no_recycling=3, max_templates=4, config_preset=seq_model_esm1b_ptm       
PARENT                                                                          
MODEL     1                                                                     
ATOM      1  N   LEU A   1      -7.388  -6.344  26.614  1.00 52.77           N  
ATOM      2  CA  LEU A   1      -8.453  -6.114  27.583  1.00 52.77           C  
ATOM      3  C   LEU A   1      -9.341  -4.953  27.149  1.00 52.77           C  
ATOM      4  CB  LEU A   1      -7.865  -5.832  28.969  1.00 52.77           C  
ATOM      5  O   LEU A   1     -10.532  -4.924  27.467  1.00 52.77           O  
ATOM      6  CG  LEU A   1      -7.576  -7.053  29.844  1.00 52.77           C  
ATOM      7  CD1 LEU A   1      -6.452  -6.746  30.827  1.00 52.77           C  
ATOM      8  CD2 LEU A   1      -8.836  -7.491  30.583  1.00 52.77           C  
......
......
ATOM   2578  O   LEU A 327     -24.490 -32.688  12.438  1.00 24.20           O  
ATOM   2579  CG  LEU A 327     -24.755 -28.116  12.914  1.00 24.20           C  
ATOM   2580  CD1 LEU A 327     -25.522 -27.364  11.831  1.00 24.20           C  
ATOM   2581  CD2 LEU A 327     -25.168 -27.635  14.301  1.00 24.20           C  
TER    2582      LEU A 327                                                      
ENDMDL                                                                          
END                                                                             
`

Could you please help me check if this appears to be a reasonable 3D structure converted from the protein sequence? I’d greatly appreciate your help!

**Comment by zzzendurance** [comment]
Thank you very much for pointing that out! I have resolved the issue with data/pdb_mmcif/mmcif_files/ following your suggestion.

While running the code, I also encountered another error:
ValueError: Amber minimization can only be performed on proteins with well-defined residues. This protein contains at least one residue with no atoms.
I fixed it by adding the --skip_relaxation flag to the original command. After doing this, the predicted PDB files were successfully generated.

I opened these PDB files in a text editor to take a quick look, but due to my limited experience, I'm not sure whether the generated structures are correct. The content looks roughly like this:

![Image](https://github.com/user-attachments/assets/9ae6a8c2-cfe2-411f-b2ff-8dd8048ae110)

![Image](https://github.com/user-attachments/assets/4e4de0b1-31c0-4975-a1fb-3d1e55afc40f)

Could you please help me check if this appears to be a reasonable 3D structure converted from the protein sequence? I’d greatly appreciate your help!

**Comment by zzzendurance** [comment]
@vaclavhanzl 

Thank you very much for pointing that out! I have resolved the issue with data/pdb_mmcif/mmcif_files/ following your suggestion.

While running the code, I also encountered another error:
ValueError: Amber minimization can only be performed on proteins with well-defined residues. This protein contains at least one residue with no atoms.
I fixed it by adding the --skip_relaxation flag to the original command. After doing this, the predicted PDB files were successfully generated.

I opened these PDB files in a text editor to take a quick look, but due to my limited experience, I'm not sure whether the generated structures are correct. The content looks roughly like this:

![Image](https://github.com/user-attachments/assets/deba7d5e-1059-48fe-894c-190054c435d6)


![Image](https://github.com/user-attachments/assets/829e2247-0038-470d-9d12-faa0eff79efd) 

Could you please help me check if this appears to be a reasonable 3D structure converted from the protein sequence? I’d greatly appreciate your help!

**Comment by vaclavhanzl** [comment]
@zzzendurance Looks reasonable. Try to open it in pymol to find out.

**Comment by vaclavhanzl** [comment]
@zzzendurance Unless you have ways to verify the structure beyond the OpenFold prediction, maybe the ESM embedding made from the sequence only is what you want? It has an idea of the structure in it, including latent alternatives. You can easily compute it with OpenFold: https://openfold.readthedocs.io/en/latest/Single_Sequence_Inference.html
