### ISSUE TITLE
Pickling error in Docker? 

### ISSUE THREAD

**Issue by tonyageall** [aqlaboratory/openfold#423]
When I build the docker image and try to run open fold this is my error. Has anyone else experienced this? what is the work around?

[2024-03-28 16:02:57,801] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/opt/openfold/run_pretrained_openfold.py", line 471, in <module>
    main(args)
  File "/opt/openfold/run_pretrained_openfold.py", line 268, in main
    for model, output_directory in model_generator:
  File "/opt/openfold/openfold/utils/script_utils.py", line 97, in load_models_from_command_line
    d = torch.load(ckpt_path)
  File "/opt/conda/lib/python3.9/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.9/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by eamag** [comment]
What command do you run to train? That looks like a corrupted checkpoint error
