### ISSUE TITLE
Alignment error during inference

### ISSUE THREAD

**Issue by dthorburn** [aqlaboratory/openfold#441]
I've been trying to get openfold to install and run on an RTX4090 or an L4, so I've been using the `pl_upgrades` branch. The unit tests pass, but when I try to run the inference pipeline it fails. 

```
FASTA_DIR=/home/miles/localopenfold/fastas
OUT_DIR=/home/miles/localopenfold/of2_out

python3 run_pretrained_openfold.py \
    ${FASTA_DIR} \
    data/pdb_mmcif/mmcif_files/ \
    --config_preset model_1_ptm \
    --model_device "cuda:0" \
    --uniclust30_database_path /mnt/of2-dbs/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
    --output_dir ${OUT_DIR}/
```
I read that the databases are optional, but I've tried with uniclust30, uniref90, and a combination, but I get the same errors. The fasta files in the `FASTA_DIR` are small single sequence fasta files. 

Here is the error:
```
[2024-05-16 11:27:34,129] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
INFO:/home/miles/localopenfold/openfold/openfold/utils/script_utils.py:Successfully loaded JAX parameters at openfold/resources/params/params_model_1_ptm.npz...
INFO:/home/miles/localopenfold/openfold/run_pretrained_openfold.py:Generating alignments for WPB05329...
Traceback (most recent call last):
  File "/home/miles/localopenfold/openfold/run_pretrained_openfold.py", line 493, in <module>
    main(args)
  File "/home/miles/localopenfold/openfold/run_pretrained_openfold.py", line 291, in main
    precompute_alignments(tags, seqs, alignment_dir, args)
  File "/home/miles/localopenfold/openfold/run_pretrained_openfold.py", line 81, in precompute_alignments
    template_searcher = hhsearch.HHSearch(
  File "/home/miles/localopenfold/openfold/openfold/data/tools/hhsearch.py", line 58, in __init__
    if not glob.glob(database_path + "_*"):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
All the additional tool binary paths are already in `PATH`. For example,
```
$ which hhsearch
/home/miles/localopenfold/conda/envs/openfold_plup121/bin/hhsearch
```

**Comment by dthorburn** [comment]
Turns out with PDB70 path it appears to work. I guess not all databases are optional. 

Having the following in the command worked. 
```
    --uniref90_database_path data/uniref90/uniref90.fasta \
    --uniclust30_database_path /mnt/of2-dbs/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
    --pdb70_database_path /mnt/of2-dbs/pdb70/pdb70
 ```
