### ISSUE TITLE
ModuleNotFoundError: No module named 'attn_core_inplace_cuda'

### ISSUE THREAD

**Issue by agustin-ormazabal** [aqlaboratory/openfold#451]
Hello, there! I am trying to perform OpenFold, and I've already installed it according to the implementation proposed in the tutorial. During the running, it stops in this step:

Traceback (most recent call last):
  File "/nfs/research/agb/research/agustin/2024/Mycoplasma_pneumoniae_proteome/OpenFold/openfold/run_pretrained_openfold.py", line 46, in <module>
    from openfold.utils.script_utils import (load_models_from_command_line, parse_fasta, run_model,
  File "/nfs/research/agb/research/agustin/2024/Mycoplasma_pneumoniae_proteome/OpenFold/openfold/openfold/utils/script_utils.py", line 10, in <module>
    from openfold.model.model import AlphaFold
  File "/nfs/research/agb/research/agustin/2024/Mycoplasma_pneumoniae_proteome/OpenFold/openfold/openfold/model/model.py", line 29, in <module>
    from openfold.model.embedders import (
  File "/nfs/research/agb/research/agustin/2024/Mycoplasma_pneumoniae_proteome/OpenFold/openfold/openfold/model/embedders.py", line 29, in <module>
    from openfold.model.primitives import Linear, LayerNorm
  File "/nfs/research/agb/research/agustin/2024/Mycoplasma_pneumoniae_proteome/OpenFold/openfold/openfold/model/primitives.py", line 38, in <module>
    from openfold.utils.kernel.attention_core import attention_core
  File "/nfs/research/agb/research/agustin/2024/Mycoplasma_pneumoniae_proteome/OpenFold/openfold/openfold/utils/kernel/attention_core.py", line 20, in <module>
    attn_core_inplace_cuda = importlib.import_module("attn_core_inplace_cuda")
  File "/nfs/research/agb/research/agustin/software/localcolabfold/colabfold-conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'attn_core_inplace_cuda'

What can be happening?

**Comment by agustin-ormazabal** [comment]
I just realised that I was not installing the third dependences. By executing the openfold/scripts/install_third_party_dependencies.sh script, the issue get solved.
