### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by abhinavb22** [aqlaboratory/openfold#462]
I tried to install openfold with the command: mamba env create -n openfold_env -f environment.yml
and I get the following error:

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: | By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/scratch/user/abhinav22/.conda/envs/openfold_env/bin/python', '-m', 'pip', 'install', '-U', '-r', '/scratch/user/abhinav22/openfold/openfold-main/condaenv.zagfsdj3.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting git+https://github.com/NVIDIA/dllogger.git (from -r /scratch/user/abhinav22/openfold/openfold-main/condaenv.zagfsdj3.requirements.txt (line 3))
  Cloning https://github.com/NVIDIA/dllogger.git to /tmp/pip-req-build-hble364q
  Resolved https://github.com/NVIDIA/dllogger.git to commit 0540a43971f4a8a16693a9de9de73c1072020769
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting git+https://github.com/Dao-AILab/flash-attention.git@5b838a8 (from -r /scratch/user/abhinav22/openfold/openfold-main/condaenv.zagfsdj3.requirements.txt (line 4))
  Cloning https://github.com/Dao-AILab/flash-attention.git (to revision 5b838a8) to /tmp/pip-req-build-lzk44cln
  Resolved https://github.com/Dao-AILab/flash-attention.git to commit 5b838a8
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): still running...
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA/dllogger.git /tmp/pip-req-build-hble364q
  Running command git clone --filter=blob:none --quiet https://github.com/Dao-AILab/flash-attention.git /tmp/pip-req-build-lzk44cln
  WARNING: Did not find branch or tag '5b838a8', assuming revision or ref.
  Running command git checkout -q 5b838a8
  Running command git submodule update --init --recursive -q
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-lzk44cln/setup.py", line 105, in <module>
          raise_if_cuda_home_none("flash_attn")
        File "/tmp/pip-req-build-lzk44cln/setup.py", line 55, in raise_if_cuda_home_none
          raise RuntimeError(
      RuntimeError: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
      
      
      torch.__version__  = 1.12.1
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed

How can I fix this?

**Comment by cyrpaut** [comment]
Hello,
I'm also facing similar issues in installing in standalone. In that case I can think that I'm doing something wrong.
But we get similar errors on Docker:
```shell
(base) ➜  openfold git:(main) ✗ sudo docker build -t openfold .
[+] Building 223.4s (12/21)                                                                                                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                  0.0s
 => => transferring dockerfile: 1.92kB                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.3.1-cudnn8-devel-ubuntu18.04                                                                                                                0.8s
 => [internal] load .dockerignore                                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                                       0.0s
 => [ 1/17] FROM docker.io/nvidia/cuda:11.3.1-cudnn8-devel-ubuntu18.04@sha256:69cd988555eabe116f76acc754b363eee75f37674c23adb2b523f5fa32543984                                                        0.0s
 => [internal] load build context                                                                                                                                                                     0.0s
 => => transferring context: 8.71kB                                                                                                                                                                   0.0s
 => CACHED [ 2/17] RUN apt-key del 7fa2af80                                                                                                                                                           0.0s
 => CACHED [ 3/17] RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub                                                               0.0s
 => CACHED [ 4/17] RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub                                                               0.0s
 => CACHED [ 5/17] RUN apt-get update && apt-get install -y wget libxml2 cuda-minimal-build-11-3 libcusparse-dev-11-3 libcublas-dev-11-3 libcusolver-dev-11-3 git                                     0.0s
 => CACHED [ 6/17] RUN wget -P /tmp     "https://github.com/conda-forge/miniforge/releases/download/23.3.1-1/Miniforge3-Linux-x86_64.sh"     && bash /tmp/Miniforge3-Linux-x86_64.sh -b -p /opt/cond  0.0s
 => [ 7/17] COPY environment.yml /opt/openfold/environment.yml                                                                                                                                        0.1s
 => ERROR [ 8/17] RUN mamba env update -n base --file /opt/openfold/environment.yml && mamba clean --all                                                                                            222.4s
------                                                                                                                                                                                                     
 > [ 8/17] RUN mamba env update -n base --file /opt/openfold/environment.yml && mamba clean --all:                                                                                                         
21.63                                                                                                                                                                                                      
21.63                                                                                                                                                                                                      
21.63 Looking for: ['python=3.9', 'libgcc=7.2', 'setuptools=59.5.0', 'pip', 'openmm=7.7', 'pdbfixer', 'pytorch-lightning', 'biopython', 'numpy', 'pandas', 'pyyaml==5.4.1', 'requests', 'scipy==1.7', 'tqdm==4.62.2', 'typing-extensions==4.0', 'wandb', 'modelcif==0.7', 'awscli', 'ml-collections', 'aria2', 'mkl=2024.0', 'git', 'bioconda::hmmer==3.3.2', 'bioconda::hhsuite==3.3.0', 'bioconda::kalign2==2.04', 'bioconda::mmseqs2', 'pytorch::pytorch=1.13.1']
21.63 
21.63 
38.14 Transaction
38.14 
38.14   Prefix: /opt/conda
38.14 
38.14   Updating specs:
38.14 
38.14    - libgcc=7.2
38.14    - openmm=7.7
38.14    - pdbfixer
38.14    - pytorch-lightning
38.14    - biopython
38.14    - numpy
38.14    - pandas
38.14    - pyyaml==5.4.1
38.14    - scipy==1.7
38.14    - typing-extensions==4.0
38.14    - wandb
38.14    - modelcif==0.7
38.14    - awscli
38.14    - ml-collections
38.14    - aria2
38.14    - mkl=2024.0
38.14    - git
38.14    - bioconda::hmmer==3.3.2
38.14    - bioconda::hhsuite==3.3.0
38.14    - bioconda::kalign2==2.04
38.14    - bioconda::mmseqs2
38.14    - pytorch::pytorch=1.13.1
38.14    - python=3.9
38.14    - setuptools=59.5.0
38.14    - pip
38.14    - requests
38.14    - tqdm==4.62.2
38.14 
38.14 
38.15   Package                         Version  Build                  Channel                    Size
38.15 ───────────────────────────────────────────────────────────────────────────────────────────────────
38.15   Install:
38.15 ───────────────────────────────────────────────────────────────────────────────────────────────────
38.15 
38.15   + absl-py                         2.1.0  pyhd8ed1ab_0           conda-forge/noarch        107kB
38.15   + appdirs                         1.4.4  pyh9f0ad1d_0           conda-forge/noarch         13kB
38.15   + aria2                          1.37.0  h347180d_1             conda-forge/linux-64        2MB
38.15   + aws-c-auth                     0.7.22  h9137712_5             conda-forge/linux-64      106kB
38.15   + aws-c-cal                      0.6.15  h88a6e22_0             conda-forge/linux-64       47kB
38.15   + aws-c-common                   0.9.19  h4ab18f5_0             conda-forge/linux-64      226kB
38.15   + aws-c-compression              0.2.18  h83b837d_6             conda-forge/linux-64       19kB
38.15   + aws-c-event-stream              0.4.2  h0cbf018_13            conda-forge/linux-64       54kB
38.15   + aws-c-http                      0.8.2  h360477d_2             conda-forge/linux-64      195kB
38.15   + aws-c-io                       0.14.9  h2d549f9_2             conda-forge/linux-64      158kB
38.15   + aws-c-mqtt                     0.10.4  hf85b563_6             conda-forge/linux-64      164kB
38.15   + aws-c-s3                       0.5.10  h679ed35_3             conda-forge/linux-64      110kB
38.15   + aws-c-sdkutils                 0.1.16  h83b837d_2             conda-forge/linux-64       55kB
38.15   + aws-checksums                  0.1.18  h83b837d_6             conda-forge/linux-64       50kB
38.15   + awscli                         2.17.5  py39hf3d152e_0         conda-forge/linux-64       12MB
38.15   + awscrt                        0.20.10  py39hdd0344b_6         conda-forge/linux-64      172kB
38.15   + biopython                        1.83  py39hd1e30aa_0         conda-forge/linux-64        3MB
38.15   + blas                            2.121  mkl                    conda-forge/linux-64       15kB
38.15   + blas-devel                      3.9.0  21_linux64_mkl         conda-forge/linux-64       14kB
38.15   + click                           8.1.7  unix_pyh707e725_0      conda-forge/noarch         84kB
38.15   + contextlib2                    21.6.0  pyhd8ed1ab_0           conda-forge/noarch         16kB
38.15   + cudatoolkit                    11.8.0  h4ba93d1_13            conda-forge/linux-64      716MB
38.15   + distro                          1.8.0  pyhd8ed1ab_0           conda-forge/noarch         41kB
38.15   + docker-pycreds                  0.4.0  py_0                   conda-forge/noarch         11kB
38.15   + docutils                         0.19  py39hf3d152e_1         conda-forge/linux-64      760kB
38.15   + fftw                           3.3.10  nompi_hf1063bd_110     conda-forge/linux-64        2MB
38.15   + fsspec                       2024.6.1  pyhff2d567_0           conda-forge/noarch        133kB
38.15   + gawk                            5.3.0  ha916aea_0             conda-forge/linux-64        1MB
38.15   + gettext                        0.22.5  h59595ed_2             conda-forge/linux-64      475kB
38.15   + gettext-tools                  0.22.5  h59595ed_2             conda-forge/linux-64        3MB
38.15   + git                            2.45.1  pl5321hef9f9f3_0       conda-forge/linux-64       10MB
38.15   + gitdb                          4.0.11  pyhd8ed1ab_0           conda-forge/noarch         53kB
38.15   + gitpython                      3.1.43  pyhd8ed1ab_0           conda-forge/noarch        157kB
38.15   + gmp                             6.3.0  hac33072_2             conda-forge/linux-64      460kB
38.15   + hhsuite                         3.3.0  py39pl5321h0dd7abe_11  bioconda/linux-64          28MB
38.15   + hmmer                           3.3.2  hdbdd923_4             bioconda/linux-64          10MB
38.15   + ihm                               1.2  py39hd3abc70_1         conda-forge/linux-64      303kB
38.15   + jmespath                        1.0.1  pyhd8ed1ab_0           conda-forge/noarch         21kB
38.15   + kalign2                          2.04  h031d066_6             bioconda/linux-64         106kB
38.15   + libabseil                  20240116.2  cxx17_h59595ed_0       conda-forge/linux-64        1MB
38.15   + libasprintf                    0.22.5  h661eb56_2             conda-forge/linux-64       43kB
38.15   + libasprintf-devel              0.22.5  h661eb56_2             conda-forge/linux-64       34kB
38.15   + libblas                         3.9.0  21_linux64_mkl         conda-forge/linux-64       15kB
38.15   + libcblas                        3.9.0  21_linux64_mkl         conda-forge/linux-64       15kB
38.15   + libexpat                        2.6.2  h59595ed_0             conda-forge/linux-64       74kB
38.15   + libgcc                          7.2.0  h69d50b8_2             conda-forge/linux-64      312kB
38.15   + libgettextpo                   0.22.5  h59595ed_2             conda-forge/linux-64      171kB
38.15   + libgettextpo-devel             0.22.5  h59595ed_2             conda-forge/linux-64       37kB
38.15   + libgfortran-ng                 13.2.0  h69a702a_0             conda-forge/linux-64       23kB
38.15   + libgfortran5                   13.2.0  ha4646dd_0             conda-forge/linux-64        1MB
38.15   + libhwloc                       2.10.0  default_h5622ce7_1001  conda-forge/linux-64        2MB
38.15   + libidn2                         2.3.7  hd590300_0             conda-forge/linux-64      127kB
38.15   + liblapack                       3.9.0  21_linux64_mkl         conda-forge/linux-64       15kB
38.15   + liblapacke                      3.9.0  21_linux64_mkl         conda-forge/linux-64       15kB
38.15   + libprotobuf                    4.25.3  h08a7969_0             conda-forge/linux-64        3MB
38.15   + libunistring                   0.9.10  h7f98852_0             conda-forge/linux-64        1MB
38.15   + libxcrypt                      4.4.36  hd590300_1             conda-forge/linux-64      100kB
38.15   + lightning-utilities      0.11.3.post0  pyhd8ed1ab_0           conda-forge/noarch         27kB
38.15   + llvm-openmp                    18.1.7  ha31de31_0             conda-forge/linux-64       59MB
38.15   + mkl                          2024.0.0  ha957f24_49657         conda-forge/linux-64      126MB
38.15   + mkl-devel                    2024.0.0  ha770c72_49657         conda-forge/linux-64       32kB
38.15   + mkl-include                  2024.0.0  ha957f24_49657         conda-forge/linux-64      768kB
38.15   + ml-collections                  0.1.1  pyhd8ed1ab_0           conda-forge/noarch         67kB
38.15   + mmseqs2                      15.6f452  pl5321h6a68c12_2       bioconda/linux-64           4MB
38.15   + modelcif                          0.7  pyhd8ed1ab_0           conda-forge/noarch         36kB
38.15   + mpfr                            4.2.1  h9458935_1             conda-forge/linux-64      643kB
38.15   + msgpack-python                  1.0.8  py39h95fdab5_0         conda-forge/linux-64       96kB
38.15   + numpy                          1.26.4  py39h474f0d3_0         conda-forge/linux-64        7MB
38.15   + ocl-icd                         2.3.2  hd590300_1             conda-forge/linux-64      136kB
38.15   + ocl-icd-system                  1.0.0  1                      conda-forge/linux-64        4kB
38.15   + openmm                          7.7.0  py39h15fbce5_1         conda-forge/linux-64       12MB
38.15   + pandas                          2.2.2  py39hfc16268_1         conda-forge/linux-64       13MB
38.15   + pathtools                       0.1.2  py_1                   conda-forge/noarch          8kB
38.15   + pcre2                           10.43  hcad00b1_0             conda-forge/linux-64      951kB
38.15   + pdbfixer                        1.8.1  pyh6c4a22f_0           conda-forge/noarch        510kB
38.15   + perl                           5.32.1  7_hd590300_perl5       conda-forge/linux-64       13MB
38.15   + prompt-toolkit                 3.0.38  pyha770c72_0           conda-forge/noarch        269kB
38.15   + prompt_toolkit                 3.0.38  hd8ed1ab_0             conda-forge/noarch          6kB
38.15   + protobuf                       4.25.3  py39h1be52a0_0         conda-forge/linux-64      328kB
38.15   + psutil                          6.0.0  py39hd3abc70_0         conda-forge/linux-64      365kB
38.15   + python-dateutil                 2.8.2  pyhd8ed1ab_0           conda-forge/noarch        246kB
38.15   + python-tzdata                  2024.1  pyhd8ed1ab_0           conda-forge/noarch        144kB
38.15   + pytorch                        1.13.1  py3.9_cpu_0            pytorch/linux-64           86MB
38.15   + pytorch-lightning               2.1.4  pyhd8ed1ab_0           conda-forge/noarch        427kB
38.15   + pytorch-mutex                     1.0  cpu                    pytorch/noarch              3kB
38.15   + pytz                           2024.1  pyhd8ed1ab_0           conda-forge/noarch        189kB
38.15   + pyyaml                          5.4.1  py39hb9d737c_4         conda-forge/linux-64      189kB
38.15   + s2n                            1.4.16  he19d79f_0             conda-forge/linux-64      350kB
38.15   + scipy                           1.7.0  py39hee8e79c_1         conda-forge/linux-64       23MB
38.15   + sentry-sdk                      2.7.1  pyhd8ed1ab_0           conda-forge/noarch        192kB
38.15   + setproctitle                    1.3.3  py39hd1e30aa_0         conda-forge/linux-64       20kB
38.15   + six                            1.16.0  pyh6c4a22f_0           conda-forge/noarch         14kB
38.15   + smmap                           5.0.0  pyhd8ed1ab_0           conda-forge/noarch         22kB
38.15   + tbb                         2021.12.0  h297d8ca_1             conda-forge/linux-64      194kB
38.15   + torchmetrics              1.4.0.post0  pyhd8ed1ab_0           conda-forge/noarch        350kB
38.15   + typing-extensions               4.0.0  hd8ed1ab_0             conda-forge/noarch          8kB
38.15   + typing_extensions               4.0.0  pyha770c72_0           conda-forge/noarch         27kB
38.15   + wandb                          0.16.6  pyhd8ed1ab_0           conda-forge/noarch          2MB
38.15   + wcwidth                        0.2.13  pyhd8ed1ab_0           conda-forge/noarch         33kB
38.15   + wget                           1.21.4  hda4d442_0             conda-forge/linux-64      770kB
38.15   + yaml                            0.2.5  h7f98852_2             conda-forge/linux-64       89kB
38.15   + zlib                           1.2.13  hd590300_5             conda-forge/linux-64       93kB
38.15 
38.15   Change:
38.15 ───────────────────────────────────────────────────────────────────────────────────────────────────
38.15 
38.15   - _openmp_mutex                     4.5  2_gnu                  conda-forge                    
38.15   + _openmp_mutex                     4.5  2_kmp_llvm             conda-forge/linux-64        6kB
38.15   - brotli-python                   1.1.0  py310hc6cd4ac_0        conda-forge                    
38.15   + brotli-python                   1.1.0  py39h3d6467e_1         conda-forge/linux-64      350kB
38.15   - libarchive                      3.6.2  h039dbb9_1             conda-forge                    
38.15   + libarchive                      3.6.2  h039dbb9_1             conda-forge/linux-64     Cached
38.15   - ruamel.yaml.clib                0.2.7  py310h1fa729e_1        conda-forge                    
38.15   + ruamel.yaml.clib                0.2.7  py39hd1e30aa_2         conda-forge/linux-64      144kB
38.15 
38.15   Reinstall:
38.15 ───────────────────────────────────────────────────────────────────────────────────────────────────
38.15 
38.15   o boltons                        23.0.0  pyhd8ed1ab_0           conda-forge                    
38.15   o certifi                     2023.7.22  pyhd8ed1ab_0           conda-forge                    
38.15   o charset-normalizer              3.2.0  pyhd8ed1ab_0           conda-forge                    
38.15   o colorama                        0.4.6  pyhd8ed1ab_0           conda-forge                    
38.15   o conda-libmamba-solver          23.3.0  pyhd8ed1ab_0           conda-forge                    
38.15   o conda-package-handling          2.2.0  pyh38be061_0           conda-forge                    
38.15   o conda-package-streaming         0.9.0  pyhd8ed1ab_0           conda-forge                    
38.15   o idna                              3.4  pyhd8ed1ab_0           conda-forge                    
38.15   o jsonpatch                        1.32  pyhd8ed1ab_0           conda-forge                    
38.15   o jsonpointer                       2.0  py_0                   conda-forge                    
38.15   o packaging                        23.1  pyhd8ed1ab_0           conda-forge                    
38.15   o pluggy                          1.3.0  pyhd8ed1ab_0           conda-forge                    
38.15   o pycparser                        2.21  pyhd8ed1ab_0           conda-forge                    
38.15   o pysocks                         1.7.1  pyha2e5f31_6           conda-forge                    
38.15   o toolz                          0.12.0  pyhd8ed1ab_0           conda-forge                    
38.15   o wheel                          0.41.2  pyhd8ed1ab_0           conda-forge                    
38.15 
38.15   Upgrade:
38.15 ───────────────────────────────────────────────────────────────────────────────────────────────────
38.15 
38.15   - c-ares                         1.19.1  hd590300_0             conda-forge                    
38.15   + c-ares                         1.28.1  hd590300_0             conda-forge/linux-64      169kB
38.15   - cffi                           1.15.1  py310h255011f_3        conda-forge                    
38.15   + cffi                           1.16.0  py39h7a31438_0         conda-forge/linux-64      240kB
38.15   - conda                          23.3.1  py310hff52083_0        conda-forge                    
38.15   + conda                          23.5.2  py39hf3d152e_0         conda-forge/linux-64        1MB
38.15   - libcurl                         8.2.1  hca28451_0             conda-forge                    
38.15   + libcurl                         8.8.0  hca28451_0             conda-forge/linux-64      406kB
38.15   - libmamba                        1.4.2  hcea66bb_0             conda-forge                    
38.15   + libmamba                        1.5.0  h658169a_0             conda-forge/linux-64        2MB
38.15   - libmambapy                      1.4.2  py310h1428755_0        conda-forge                    
38.15   + libmambapy                      1.5.0  py39h78efd80_0         conda-forge/linux-64      297kB
38.15   - libnghttp2                     1.52.0  h61bc06f_0             conda-forge                    
38.15   + libnghttp2                     1.58.0  h47da74e_1             conda-forge/linux-64      632kB
38.15   - libnsl                          2.0.0  h7f98852_0             conda-forge                    
38.15   + libnsl                          2.0.1  hd590300_0             conda-forge/linux-64       33kB
38.15   - libsqlite                      3.43.0  h2797004_0             conda-forge                    
38.15   + libsqlite                      3.46.0  hde9e2c9_0             conda-forge/linux-64      865kB
38.15   - libxml2                        2.11.5  h232c23b_1             conda-forge                    
38.15   + libxml2                        2.12.7  hc051c1a_1             conda-forge/linux-64      705kB
38.15   - mamba                           1.4.2  py310h51d5547_0        conda-forge                    
38.15   + mamba                           1.5.0  py39hc5d2bb1_0         conda-forge/linux-64       51kB
38.15   - ncurses                           6.4  hcb278e6_0             conda-forge                    
38.15   + ncurses                           6.5  h59595ed_0             conda-forge/linux-64      887kB
38.15   - openssl                         3.1.2  hd590300_0             conda-forge                    
38.15   + openssl                         3.3.1  h4ab18f5_1             conda-forge/linux-64        3MB
38.15   - pip                            23.2.1  pyhd8ed1ab_0           conda-forge                    
38.15   + pip                              24.0  pyhd8ed1ab_0           conda-forge/noarch          1MB
38.15   - pycosat                         0.6.4  py310h5764c6d_1        conda-forge                    
38.15   + pycosat                         0.6.6  py39hd1e30aa_0         conda-forge/linux-64       85kB
38.15   - requests                       2.31.0  pyhd8ed1ab_0           conda-forge                    
38.15   + requests                       2.32.3  pyhd8ed1ab_0           conda-forge/noarch         59kB
38.15   - tk                             8.6.12  h27826a3_0             conda-forge                    
38.15   + tk                             8.6.13  noxft_h4845f30_101     conda-forge/linux-64        3MB
38.15   - zstandard                      0.19.0  py310h5764c6d_0        conda-forge                    
38.15   + zstandard                      0.22.0  py39h81c9582_1         conda-forge/linux-64      405kB
38.15   - zstd                            1.5.5  hfc55251_0             conda-forge                    
38.15   + zstd                            1.5.6  ha6fb4c9_0             conda-forge/linux-64      555kB
38.15 
38.15   Downgrade:
38.15 ───────────────────────────────────────────────────────────────────────────────────────────────────
38.15 
38.15   - cryptography                   41.0.3  py310h75e40e8_0        conda-forge                    
38.15   + cryptography                   40.0.2  py39h079d5ae_0         conda-forge/linux-64        2MB
38.15   - pyopenssl                      23.2.0  pyhd8ed1ab_1           conda-forge                    
38.15   + pyopenssl                      23.1.1  pyhd8ed1ab_0           conda-forge/noarch        128kB
38.15   - python                        3.10.12  hd12c33a_0_cpython     conda-forge                    
38.15   + python                         3.9.19  h0755675_0_cpython     conda-forge/linux-64       24MB
38.15   - python_abi                       3.10  3_cp310                conda-forge                    
38.15   + python_abi                        3.9  4_cp39                 conda-forge/linux-64        6kB
38.15   - ruamel.yaml                   0.17.32  py310h2372a71_0        conda-forge                    
38.15   + ruamel.yaml                   0.17.21  py39h72bdee0_3         conda-forge/linux-64      188kB
38.15   - setuptools                     68.1.2  pyhd8ed1ab_0           conda-forge                    
38.15   + setuptools                     59.5.0  py39hf3d152e_0         conda-forge/linux-64        1MB
38.15   - tqdm                           4.66.1  pyhd8ed1ab_0           conda-forge                    
38.15   + tqdm                           4.62.2  pyhd8ed1ab_0           conda-forge/noarch         82kB
38.15   - urllib3                         2.0.4  pyhd8ed1ab_0           conda-forge                    
38.15   + urllib3                       1.26.19  pyhd8ed1ab_0           conda-forge/noarch        115kB
38.15 
38.15   Summary:
38.15 
38.15   Install: 102 packages
38.15   Change: 4 packages
38.15   Reinstall: 16 packages
38.15   Upgrade: 19 packages
38.15   Downgrade: 8 packages
38.15 
38.15   Total download: 1GB
38.15 
38.15 ───────────────────────────────────────────────────────────────────────────────────────────────────
38.15 
38.15 
155.6 
155.6 Downloading and Extracting Packages
155.6 
155.6 Preparing transaction: ...working... done
157.3 Verifying transaction: ...working... done
164.0 Executing transaction: ...working... By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html
206.2 
206.2 done
208.7 Installing pip dependencies: ...working... Pip subprocess error:
221.8   Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA/dllogger.git /tmp/pip-req-build-j0fdx5x9
221.8   Running command git clone --filter=blob:none --quiet https://github.com/Dao-AILab/flash-attention.git /tmp/pip-req-build-dggcmzly
221.8   Running command git submodule update --init --recursive -q
221.8   error: subprocess-exited-with-error
221.8   
221.8   × python setup.py egg_info did not run successfully.
221.8   │ exit code: 1
221.8   ╰─> [12 lines of output]
221.8       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
221.8       Traceback (most recent call last):
221.8         File "<string>", line 2, in <module>
221.8         File "<pip-setuptools-caller>", line 34, in <module>
221.8         File "/tmp/pip-req-build-dggcmzly/setup.py", line 115, in <module>
221.8           raise RuntimeError(
221.8       RuntimeError: FlashAttention is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
221.8       
221.8       
221.8       torch.__version__  = 1.13.1
221.8       
221.8       
221.8       [end of output]
221.8   
221.8   note: This error originates from a subprocess, and is likely not a problem with pip.
221.8 error: metadata-generation-failed
221.8 
221.8 × Encountered error while generating package metadata.
221.8 ╰─> See above for output.
221.8 
221.8 note: This is an issue with the package mentioned above, not pip.
221.8 hint: See above for details.
221.8 
221.8 Ran pip subprocess with arguments:
221.8 ['/opt/conda/bin/python', '-m', 'pip', 'install', '-U', '-r', '/opt/openfold/condaenv.rat1mj4_.requirements.txt', '--exists-action=b']
221.8 Pip subprocess output:
221.8 Collecting git+https://github.com/NVIDIA/dllogger.git (from -r /opt/openfold/condaenv.rat1mj4_.requirements.txt (line 3))
221.8   Cloning https://github.com/NVIDIA/dllogger.git to /tmp/pip-req-build-j0fdx5x9
221.8   Resolved https://github.com/NVIDIA/dllogger.git to commit 0540a43971f4a8a16693a9de9de73c1072020769
221.8   Preparing metadata (setup.py): started
221.8   Preparing metadata (setup.py): finished with status 'done'
221.8 Collecting git+https://github.com/Dao-AILab/flash-attention.git (from -r /opt/openfold/condaenv.rat1mj4_.requirements.txt (line 4))
221.8   Cloning https://github.com/Dao-AILab/flash-attention.git to /tmp/pip-req-build-dggcmzly
221.8   Resolved https://github.com/Dao-AILab/flash-attention.git to commit 9486635c926ad1443c5c536d90e9cefaee3db9b4
221.8   Preparing metadata (setup.py): started
221.8   Preparing metadata (setup.py): finished with status 'error'
221.8 
221.8 failed
221.8 
221.8 CondaEnvException: Pip failed
221.8 
------

 5 warnings found (use --debug to expand):
 - LegacyKeyValueFormat: "LABEL key=value" should be used instead of legacy "LABEL key value" format (line 4)
 - LegacyKeyValueFormat: "LABEL key=value" should be used instead of legacy "LABEL key value" format (line 5)
 - LegacyKeyValueFormat: "LABEL key=value" should be used instead of legacy "LABEL key value" format (line 6)
 - LegacyKeyValueFormat: "LABEL key=value" should be used instead of legacy "LABEL key value" format (line 7)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 19)
Dockerfile:24
--------------------
  22 |     
  23 |     # installing into the base environment since the docker container wont do anything other than run openfold
  24 | >>> RUN mamba env update -n base --file /opt/openfold/environment.yml && mamba clean --all
  25 |     RUN export LD_LIBRARY_PATH=${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH}
  26 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c mamba env update -n base --file /opt/openfold/environment.yml && mamba clean --all" did not complete successfully: exit code: 1

``` 
Any idea how to fix this?
Thanks

**Comment by abhinavb22** [comment]
I was able to get it running in my high performance cluster with the following commands before installation:
module purge
module load GCC/10.3.0
module load OpenMPI/4.1.1
module load CUDA/12.1.0

I also downloaded the CUDA12 version of the code with the following command:
git clone -b pl_upgrades https://github.com/aqlaboratory/openfold.git

Then follow with "mamba env create -n openfold_env -f environment.yml" and so on and it worked.

But I still could not fix this in my local workstation. I think the issue might be with incompatible versions of CUDA ???

**Comment by rafaeltiveron** [comment]
Thanks @abhinavb22, and some feel adjusts to work:

`nvcc -V` needs to call some like:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
```
If 11.8 or below, try to:
```
sudo mv /usr/bin/nvcc /usr/bin/nvcc_old
sudo ln -s /usr/local/cuda-12.5/bin/nvcc /usr/bin/nvcc
```

**Comment by vaclavhanzl** [comment]
I addressed similar issues in PR #496.

**Comment by ImeCMR** [comment]
@abhinavb22 Hi, I'm trying to install openfold in a cluster. If you have documentation for that can you please share it with me?
