### ISSUE TITLE
Some questions about running inference

### ISSUE THREAD

**Issue by wangleshuyang** [aqlaboratory/openfold#55]
When I use openfold to infer proteins, some of them can be inferred, but some of them will report errors. The reason for the error is probably: the template name searched out is outdated, and there is no outdated protein cif file in the template_mmcif_dir directory. 

Below is an example of an error protein ：
*******************5IZB_A*******************
Traceback (most recent call last):
  File "run_pretrained_openfold.py", line 253, in <module>
    main(args)
  File "run_pretrained_openfold.py", line 118, in main
    fasta_path=fasta_path, alignment_dir=local_alignment_dir
  File "/home/jsr/openfold/openfold/data/data_pipeline.py", line 420, in process_fasta
    self.template_featurizer,
  File "/home/jsr/openfold/openfold/data/data_pipeline.py", line 55, in make_template_features
    hits=hits_cat,
  File "/home/jsr/openfold/openfold/data/templates.py", line 1059, in get_templates
    kalign_binary_path=self._kalign_binary_path,
  File "/home/jsr/openfold/openfold/data/templates.py", line 827, in _process_single_hit
    with open(cif_path, "r") as cif_file:
FileNotFoundError: [Errno 2] No such file or directory: '/public/database/alphafold2_database/mmcif/mmcif_files/4zai.cif'

**Comment by gahdritz** [comment]
See #4
